[package]
name = "specte-pi"
version = "0.1.0"
edition = "2021"

[target.aarch64-unknown-linux-gnu]
linker = "/usr/bin/aarch64-linux-gnu-gcc"

[dependencies]
iced = { version = "0.10.0", features = ["canvas", "palette"] }
palette = "0.7.3"
spirit = { path = "../spirit" }
