name: Specte-rs CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  code_cleaniness_checks:
    name: Formatting Checks
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: nightly
          components: rustfmt, clippy
      - uses: actions/checkout@v4
      - run: cargo fmt --check
      - run: cargo clippy --all
  tests:
    needs: code_cleaniness_checks
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable
          components: rustfmt
          targets: wasm32-unknown-unknown
      - uses: actions/checkout@v4
      - name: Fetch Trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: 'latest'
      - run: cargo build
      - run: cargo test
